spring.application.name=eloboostum
api.prefix=/api/v1
jwt.secret=0KeY7/k9vigQUc585qvhEGXyPvUbV+zjrivXY2q347g=
jwt.duration=9999999
https.enable=false




# Db connections
spring.datasource.url=jdbc://posgres://posgres:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379




resilience4j.ratelimiter.instances.register.limit-for-period=5
resilience4j.ratelimiter.instances.register.limitRefreshPeriod= 20m
resilience4j.ratelimiter.instances.login.limit-for-period=5
resilience4j.ratelimiter.instances.login.limitRefreshPeriod= 1M
