spring.application.name=eloboostum
api.prefix=/api/v1
jwt.secret=0KeY7/k9vigQUc585qvhEGXyPvUbV+zjrivXY2q347g=
jwt.duration=9999999
https.enable=false
app.url=https://namnam.com




# Db connections
spring.datasource.url=jdbc://posgres://posgres:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379



#register
resilience4j.ratelimiter.instances.register.limit-for-period=5
resilience4j.ratelimiter.instances.register.limitRefreshPeriod= 20m
#login
resilience4j.ratelimiter.instances.login.limit-for-period=5
resilience4j.ratelimiter.instances.login.limitRefreshPeriod= 1m
#reset password
resilience4j.ratelimiter.instances.resetPassword.limit-for-period=4
resilience4j.ratelimiter.instances.resetPassword.limit-refresh-period=10m
#forgot password
resilience4j.ratelimiter.instances.forgotPasswordRequest.limit-for-period=4
resilience4j.ratelimiter.instances.forgotPasswordRequest.limit-refresh-period=10m



# Mail sending
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=<login user to smtp server>
spring.mail.password=<login password to smtp server>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
