spring.application.name=eloboostum
api.prefix=/api/v1
jwt.secret=${JWT_SECRET}
jwt.duration=9999999
app.url=https://namnam.com




# Db connections
spring.datasource.url=jdbc://posgres://posgres:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379


# Default limits
resilience4j.ratelimiter.instances.defaults.limit-for-period=5
resilience4j.ratelimiter.instances.defaults.limit-refresh-period=1m

# Only override different endpoints
resilience4j.ratelimiter.instances.register.limit-for-period=5
resilience4j.ratelimiter.instances.register.limit-refresh-period=20m

resilience4j.ratelimiter.instances.resetPassword.limit-for-period=4
resilience4j.ratelimiter.instances.resetPassword.limit-refresh-period=10m

resilience4j.ratelimiter.instances.forgotPasswordRequest.limit-for-period=4
resilience4j.ratelimiter.instances.forgotPasswordRequest.limit-refresh-period=10m
#superadmin
resilience4j.ratelimiter.instances.give-moderator.limit-for-period=4
resilience4j.ratelimiter.instances.give-moderator.limit-refresh-period=1m
resilience4j.ratelimiter.instances.remove-moderator.limit-for-period=4
resilience4j.ratelimiter.instances.remove-moderator.limit-refresh-period=1m



# Mail sending
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
